# Inteligencia Artificial

## Capítulo 2

### Matemática Básica para Ciencias de Datos

- **Unidad 1.** Introducción
- **Unidad 2.** Matemática Básica para Ciencias de Datos
- **Unidad 3.** Entendiendo las Ciencias de Datos: Vector
- **Unidad 4.** Entendiendo las Ciencias de Datos: Matriz
- **Unidad 5.** Entendiendo las Ciencias de Datos: Derivativas

# Quiz

___

## Q 02-01

### Cree ejemplos de vector cero, vector unitario, matriz cuadrada, matriz diagonal, matriz identidad y matriz simétrica uno por uno, y represente vectores y matrices con NumPy.

In [14]:
#vector cero
import numpy as np

vector_cero = np.zeros(5)
print(vector_cero)


[0. 0. 0. 0. 0.]


In [7]:
#Vector Unitario
import numpy as np

vector = np.array([3, 4])
vec_norm = np.linalg.norm(vector)
vector_unitario = vector / vec_norm

print("Vector unitario:", vector_unitario)

Vector unitario: [0.6 0.8]


In [8]:
#matriz cuadrada
import numpy as np
matriz_cuadrada = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz_cuadrada)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#Matriz diagonal
import numpy as np
matriz_diagonal = np.diag([1, 2, 3])
print(matriz_diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
#Matriz identidad
import numpy as np
matriz_identidad = np.eye(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Matriz simetrica
import numpy as np
matriz_simetrica = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print(matriz_simetrica)

[[1 2 3]
 [2 4 5]
 [3 5 6]]


## Q 02-02

### Las acciones de tres empresas A, B y C son 1 millón de wones, 800.000 wones y 500.000 wones, respectivamente. Queremos encontrar la cantidad necesaria para comprar 3, 4 y 5 acciones de estas acciones, respectivamente.

1) Exprese el precio y la cantidad de las acciones como vector p y vector n, respectivamente y codificados con NumPy.

In [15]:
import numpy as np
vector_p = np.array([1000000, 800000, 500000])
vector_n = np.array([3, 4, 5])

2) La cantidad necesaria para comprar acciones se expresa mediante multiplicación y el valor se calcula mediante la operación Numpy.

In [17]:
# Cantidad necesaria para la compra de las acciones
cantidad = vector_n * vector_p
print("Cantidad de acciones a comprar:", vector_n)
print("Precio por acción:", vector_p)
print("Cantidad necesaria para comprar las acciones:", cantidad)

Cantidad de acciones a comprar: [3 4 5]
Precio por acción: [1000000  800000  500000]
Cantidad necesaria para comprar las acciones: [3000000 3200000 2500000]


___

## Q 02-03

### Cuando se ejecuta el siguiente código, todos los datos de la imagen numérica MNIST se convierten en vectores para crear una única matriz NumPy X. Utilice esta matriz para resolver el siguiente problema.
```
from sklearn.datasets import load_digits
X=load_digits().data
```

1) Encuentre la similitud entre la primera imagen y la décima imagen usando el producto escalar.

In [35]:
from sklearn.datasets import load_digits
X=load_digits().data

In [41]:
import numpy as np

imagen_1 = X[0]  # Primera imagen
imagen_10 = X[9]  # Décima imagen

similitud = np.dot(imagen_1, imagen_10)

print("La similitud entre la primera y la décima imagen, usando el producto escalar es:", similitud)

La similitud entre la primera y la décima imagen, usando el producto escalar es: 2807.0


2) Encuentre la similitud para una combinación de todas las imágenes usando el producto escalar, ¿cómo sería eficiente implementarlo (pista: usando matrices y multiplicación de matrices)?


In [42]:
matriz_similitud = np.dot(X, X.T)

# Mostrar la matriz de similitud
print("Matriz de similitud (producto escalar):")
print(matriz_similitud)

Matriz de similitud (producto escalar):
[[3070. 1866. 2264. ... 2812. 3006. 2898.]
 [1866. 4209. 3432. ... 3906. 3083. 3307.]
 [2264. 3432. 4388. ... 4005. 3063. 3697.]
 ...
 [2812. 3906. 4005. ... 5092. 3729. 4598.]
 [3006. 3083. 3063. ... 3729. 4316. 3850.]
 [2898. 3307. 3697. ... 4598. 3850. 4938.]]


___

## Q 02-04

### Calculate the following inverse matrix.


![matrix.png](attachment:matrix.png)

In [31]:
import numpy as np

# Definir la matriz
matriz = np.array([
    [-1, 4, 0],
    [-1, 3, 1],
    [0, 3, -2]
])

print("Matriz de la imagen")
print(matriz)

#Calculamos su determinante para saber si tiene inversa
det_matriz = np.linalg.det(matriz)
print("\nDeterminante de la matriz:")
print(det_matriz)

# Como el determinante es igual a 1 se, calcula la matriz inversa
matriz_inversa = np.linalg.inv(matriz)

print("\nMatriz inversa:")
print(matriz_inversa)


Matriz de la imagen
[[-1  4  0]
 [-1  3  1]
 [ 0  3 -2]]

Determinante de la matriz:
1.0000000000000002

Matriz inversa:
[[-9.  8.  4.]
 [-2.  2.  1.]
 [-3.  3.  1.]]


___

## Q 02-05

### El problema del precio de la vivienda en Boston es un problema de predicción del precio de la vivienda en cada ciudad de Boston (EE.UU.) utilizando características como el índice de delincuencia y la contaminación atmosférica de la zona. Puede importarse del paquete scikit-learn. Encuentre el vector de pesos x cuando el problema del precio de la vivienda en Boston se resuelva con el modelo de predicción lineal Ax=b. Los datos matriciales y vectoriales pueden obtenerse como sigue. Aquí, para simplificar el problema, limitamos los datos de entrada a la tasa de criminalidad (CRIM), la calidad del aire (NOX), el número de habitaciones (RM) y la edad (AGE), y sólo se utilizaron cuatro datos.

Ejecute el código siguiente para comprobar si la magnitud o el signo del vector de pesos obtenido al ejecutar el programa se ajusta a la noción común. Para ello, interprete la salida impresa para todos los factores: CRIM, NOX, RM y EDAD.

(※ Escriba la salida interpretada como "el precio de la vivienda está en proporción inversa a la tasa de criminalidad (CRIM)").
```
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]
```

In [ ]:
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]

In [48]:
A = np.array([[0.00632,0.02731,0.02729,0.03237],[0.538,0.469,0.469,0.458],[6.575,6.421,7.185,6.998],[65.2,78.9,61.1,45.8]])

b = np.array([24., 21.6, 34.7, 33.4])

x = np.linalg.solve(A, b)
# resultados
print("Pesos para CRIM, NOX, RM y AGE:")
print(x)

Pesos para CRIM, NOX, RM y AGE:
[ -443.58948971  1306.42961934 -2737.70617156  2033.88613199]


___

## Fin